apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: latsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.latsencrypt.org/directory
    email: 'dimarakov21@gmail.com'
    privateKeySecretRef:
      name: latsencrypt-prod
    http01: {}
